### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by BabbarRaghav** [CodeWithHarry/NewsMonkey-React#1]
mere code me ek problem aa rahi hai... Agar me apna code localhost me run karu to sahi chal raha hai but agar me apna code "on your network" wale link se karu to error aa raha hai:-
TypeError: Cannot read property 'map' of undefined
Me purani video dubara dekhi sari check karne ke liye me kya galti ker raha hu per kuch nahi mil raha
Please harry bhai ya or koi help kerdo.
![image](https://user-images.githubusercontent.com/89309326/131253963-92c681d4-67ec-4c21-8c34-ed05de7ef0d6.png)

**Comment by eklavyadev** [comment]
This problem is encountered may be due to ease in using a non-strict mode
You should add `"use strict";` at the top of your react app and find what actually the error is

**Comment by gramo37** [comment]
This may be because you exhausted your api requests for the day. Check your requests left for the day in news API.

**Comment by gramo37** [comment]
If you want to continue your work you can use your brother's or any other family members details to get a new API key, and just replace the API key. It worked for me.

**Comment by Shivam2001-programmer** [comment]
Type Error: Cannot read property'map' of undefined at localhost :3000      please Bhaiya resolved this 
![16303237854781370110448877429764](https://user-images.githubusercontent.com/75406313/131334008-7c225018-d01d-4bbb-907c-0db1f5ee15a4.jpg)

**Comment by Shivam2001-programmer** [comment]
Type Error: Cannot read property'map' of undefined at localhost :3000

**Comment by eklavyadev** [comment]
https://stackoverflow.com/questions/24706267/error-cannot-read-property-map-of-undefined
I think this might solve your problems

**Comment by WindingSnow** [comment]
@Shivam2001-programmer The news API only works at your localhost.
