### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by janender0707** [CodeWithHarry/NewsMonkey-React#11]
50 | <h1 className="text-center" style={{ margin: '35px 0px', marginTop: '90px' }}>NewsMonkey - Top {capitalizeFirstLetter(props.category)} Headlines</h1>
  51 | {loading && <Spinner />}
  52 | <InfiniteScroll
> 53 |     dataLength={articles.length}
     | ^  54 |     next={fetchMoreData}
  55 |     hasMore={articles.length !== totalResults}
  56 |     loader={<Spinner/>}

**Comment by steven971998** [comment]
you got solution for this? Please give bro.
